"use client";

import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import {
  AlertTriangle,
  Check,
  CircleDashed,
  ClipboardList,
  FileText,
  LoaderCircle,
  Minus,
  Send,
  Stethoscope,
  Trash2,
  Upload,
  Users,
} from "lucide-react";
import { ActionPanel, ConfidenceBar, DashboardCard, MetricCard, StepTracker, StatusChip } from "@/components/dashboard/SharedDashboard";
import { SkeletonBlock, SkeletonCard } from "@/components/ui/Skeleton";
import usePageReady from "@/hooks/usePageReady";
import { getCurrentUser } from "@/lib/api/auth";
import { addClaimDocument, submitClaim } from "@/lib/api/claims";
import { formatCurrency, formatRelativeTime } from "@/lib/claimUi";
import { canRoleUploadForClaim, getLatestInsurerDocumentRequest, getQueryOwnerRole, getSharedDocuments, isPdfFile } from "@/lib/claimSync";
import {
  MOCK_ONGOING_PATIENTS,
  PHASE_LABELS,
  PHASE_ORDER,
  REIMBURSEMENT_REQUIRED_DOCS,
  resolveHospitalScenario,
  type DischargeSummaryFields,
  type OngoingPatient,
  type OngoingPatientPhase,
} from "@/lib/dashboardContent";
import {
  createWorkflowClaimInput,
  getDemoCaseById,
  loadDemoDocumentCorpus,
  resolveViewerForRole,
  setActiveDemoCaseId,
  type DemoUploadSelection,
} from "@/lib/demoWorkflow";
import { useAppStore } from "@/store/useAppStore";
import type { AppUser, Claim } from "@/types";

/* ------------------------------------------------------------------ */
/*  Helpers                                                            */
/* ------------------------------------------------------------------ */

type UploadStatus = "missing" | "scanning" | "ready" | "issue";

type UploadItem = {
  slotId: string;
  fileName: string;
  type: string;
  size: number;
  status: UploadStatus;
};

type HospitalTab = "ongoing" | "submit" | "track";
type ClaimServiceType = "cashless" | "reimbursement";

const trackSteps = (claim: Claim) => [
  { label: "Submitted", state: "complete" as const },
  { label: "Documents verified", state: claim.documents.length > 0 ? "complete" as const : "active" as const },
  { label: "Policy checked", state: claim.status !== "pending" ? "complete" as const : "active" as const },
  { label: claim.status === "denied" ? "Denied" : claim.status === "approved" ? "Approved" : "Manual review", state: claim.status === "pending" ? "upcoming" as const : "complete" as const },
  { label: "Payment sent", state: claim.status === "approved" ? "complete" as const : "upcoming" as const },
];

const statusChipTone = (status: Claim["status"]): "green" | "red" | "amber" | "blue" =>
  status === "approved" ? "green" : status === "denied" ? "red" : status === "under_review" ? "amber" : "blue";

const phaseTone = (phase: OngoingPatientPhase): "blue" | "green" | "amber" | "red" =>
  phase === "pre_admission" ? "blue" : phase === "admitted" ? "amber" : phase === "during_stay" ? "amber" : "green";

const hospitalCashlessFlow = [
  "AL No. generated by hospital",
  "Re-auth form attached",
  "Prescription reports uploaded",
  "Diagnoses recorded under patient admit",
  "Insurance initial amount request triggered",
  "Tests and billings updated during stay",
  "Discharge summary sent to insurance",
];

const reimbursementCriticalFields = ["No. of days", "Medicine", "Diagnosis", "Hospitals"];

/* ------------------------------------------------------------------ */
/*  Component                                                          */
/* ------------------------------------------------------------------ */

export default function HospitalDashboardPage() {
  const ready = usePageReady();
  const claims = useAppStore((state) => state.claims);
  const [viewer, setViewer] = useState<AppUser | null>(null);
  const [corpusLoaded, setCorpusLoaded] = useState(false);
  const [activeTab, setActiveTab] = useState<HospitalTab>("ongoing");
  const [claimServiceType, setClaimServiceType] = useState<ClaimServiceType>("cashless");
  const [selectedClaimId, setSelectedClaimId] = useState<string | null>(null);
  const [previewDocId, setPreviewDocId] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);
  const [form, setForm] = useState({
    patientName: "Arjun Mehta",
    policyNumber: "HDFC-ERGO-2025-991203",
    hospital: "City Care Hospital, Mumbai",
    diagnosis: "Dengue Fever with Thrombocytopenia",
    requestedAmount: 22150,
  });
  const [uploads, setUploads] = useState<Record<string, UploadItem>>({});

  // Ongoing patients state
  const [ongoingPatients, setOngoingPatients] = useState<OngoingPatient[]>(MOCK_ONGOING_PATIENTS);
  const [selectedPatientId, setSelectedPatientId] = useState<string | null>(MOCK_ONGOING_PATIENTS[0]?.id ?? null);
  const [dischargeDraft, setDischargeDraft] = useState<Partial<DischargeSummaryFields>>({});

  useEffect(() => {
    getCurrentUser().then((currentUser) => {
      const resolvedViewer = resolveViewerForRole("hospital", currentUser);
      setViewer(resolvedViewer);
      if (resolvedViewer?.name) {
        setForm((current) => ({ ...current, hospital: resolvedViewer.name }));
      }
    });
    loadDemoDocumentCorpus().then(() => setCorpusLoaded(true));
  }, []);

  const scenarioId = useMemo(() => resolveHospitalScenario(form.diagnosis, Number(form.requestedAmount)), [form.diagnosis, form.requestedAmount]);
  const demoCase = getDemoCaseById(scenarioId);
  const workflowClaims = useMemo(
    () => [...claims]
      .sort((left, right) => new Date(right.submittedAt).getTime() - new Date(left.submittedAt).getTime()),
    [claims],
  );
  const selectedClaim = workflowClaims.find((claim) => claim.id === selectedClaimId) ?? workflowClaims[0] ?? null;
  const selectedClaimDocuments = selectedClaim ? getSharedDocuments(selectedClaim) : [];
  const selectedClaimRequest = selectedClaim ? getLatestInsurerDocumentRequest(selectedClaim) : null;
  const hospitalCanUploadToClaim = selectedClaim ? canRoleUploadForClaim(selectedClaim, "hospital") : false;
  const selectedClaimQueryOwner = selectedClaim ? getQueryOwnerRole(selectedClaim) : "hospital";
  const selectedPatient = ongoingPatients.find((patient) => patient.id === selectedPatientId) ?? ongoingPatients[0] ?? null;

  // Metrics
  const approvedToday = workflowClaims.filter((claim) => claim.status === "approved").reduce((sum, claim) => sum + (claim.amountApproved ?? 0), 0);
  const ongoingCount = ongoingPatients.length;
  const pendingAlCount = ongoingPatients.filter((p) => p.phase === "pre_admission").length;
  const awaitingDischarge = ongoingPatients.filter((p) => p.phase === "during_stay" || p.phase === "admitted").length;
  const hospitalVerificationReady = Boolean(viewer?.hospitalRegistrationId && viewer?.npi);
  const reimbursementPacketReady = REIMBURSEMENT_REQUIRED_DOCS.every((item) => uploads[item.slotId] && uploads[item.slotId].status !== "scanning");

  // For submit tab
  const currentDocRequirements = claimServiceType === "reimbursement" ? REIMBURSEMENT_REQUIRED_DOCS : demoCase.requiredDocuments;
  const readyDocuments = currentDocRequirements.filter((item) => uploads[item.slotId] && uploads[item.slotId].status !== "scanning").length;
  const allRequiredUploaded = currentDocRequirements.every((item) => uploads[item.slotId] && uploads[item.slotId].status !== "scanning");
  const hasDocumentIssues = currentDocRequirements.some((item) => uploads[item.slotId]?.status === "issue");
  const submissionConfidence = scenarioId === "case-3" ? 94 : scenarioId === "case-2" ? 68 : 88;
  const confidenceTone = submissionConfidence >= 90 ? "green" : submissionConfidence >= 75 ? "blue" : "amber";

  const commandStats = [
    {
      label: "Ongoing patients",
      value: ongoingCount,
      tone: "blue" as const,
      badge: "Active",
      helper: "Current cashless cases being managed in hospital.",
      className: "bg-[linear-gradient(180deg,#ffffff_0%,#eaf4ff_100%)]",
    },
    {
      label: "Pending AL numbers",
      value: pendingAlCount,
      tone: pendingAlCount > 0 ? "amber" as const : "green" as const,
      badge: pendingAlCount > 0 ? "Pre-admit" : "Clear",
      helper: pendingAlCount > 0 ? "Patients still in pre-admission needing hospital-generated AL numbers." : "All patients have active AL numbers.",
      className: pendingAlCount > 0 ? "bg-[linear-gradient(180deg,#ffffff_0%,#fff4e6_100%)]" : "bg-[linear-gradient(180deg,#ffffff_0%,#f8fafc_100%)]",
    },
    {
      label: "Awaiting discharge",
      value: awaitingDischarge,
      tone: "amber" as const,
      badge: "In-stay",
      helper: "Patients currently admitted or in active treatment.",
      className: "bg-[linear-gradient(180deg,#ffffff_0%,#fff8eb_100%)]",
    },
    {
      label: "Insurance release",
      value: "40-50%",
      tone: "green" as const,
      badge: "40-50%",
      helper: "Admit trigger is used to push the initial insurer amount release.",
      className: "bg-[linear-gradient(180deg,#ffffff_0%,#ecfbf1_100%)]",
    },
    {
      label: "Total approved today",
      value: formatCurrency(approvedToday),
      tone: "blue" as const,
      badge: "Released",
      helper: "Settlement value already cleared today.",
      className: "bg-[linear-gradient(180deg,#ffffff_0%,#eef6ff_100%)]",
      valueClassName: "text-[17px] sm:text-[18px]",
    },
  ];

  useEffect(() => {
    setUploads((current) => {
      const next = { ...current };
      for (const key of Object.keys(next)) {
        if (!currentDocRequirements.find((item) => item.slotId === key)) {
          delete next[key];
        }
      }
      return next;
    });
  }, [currentDocRequirements]);

  const updateUploadStatus = (slotId: string, status: UploadStatus) => {
    setUploads((current) => ({
      ...current,
      [slotId]: {
        ...current[slotId],
        status,
      },
    }));
  };

  const handleFileSelect = (slotId: string, file?: File | null) => {
    if (!file) {
      return;
    }

    if (!isPdfFile(file)) {
      toast.error("Upload a PDF file.");
      return;
    }

    setUploads((current) => ({
      ...current,
      [slotId]: {
        slotId,
        fileName: file.name,
        type: "application/pdf",
        size: file.size,
        status: "scanning",
      },
    }));

    window.setTimeout(() => {
      const shouldFlag = resolveHospitalScenario(form.diagnosis, Number(form.requestedAmount)) === "case-2" && slotId === "billing";
      updateUploadStatus(slotId, shouldFlag ? "issue" : "ready");
    }, 1200);
  };

  const removeUpload = (slotId: string) => {
    setUploads((current) => {
      const next = { ...current };
      delete next[slotId];
      return next;
    });
  };

  const handleRespondToInsurerRequest = async (file?: File | null) => {
    if (!selectedClaim || !file) {
      return;
    }

    if (!isPdfFile(file)) {
      toast.error("Upload a PDF file.");
      return;
    }

    await addClaimDocument(
      selectedClaim.id,
      {
        name: file.name,
        type: "application/pdf",
        size: file.size,
        uploadedAt: new Date().toISOString(),
        uploadedBy: "hospital",
        category: "Hospital Response PDF",
        processingStatus: "ready",
      },
      "hospital",
    );
    toast.success("Hospital PDF added to the shared claim record.");
  };

  const handleSubmit = async () => {
    if (!allRequiredUploaded || !corpusLoaded || submitting) {
      return;
    }

    try {
      setSubmitting(true);
      setActiveDemoCaseId(scenarioId);
      const corpus = await loadDemoDocumentCorpus();
      const uploadPayload = demoCase.requiredDocuments.map<DemoUploadSelection>((item) => ({
        slotId: item.slotId,
        fileName: uploads[item.slotId]?.fileName ?? "document.pdf",
        type: uploads[item.slotId]?.type ?? "application/pdf",
        size: uploads[item.slotId]?.size ?? 100000,
      }));

      const claimInput = createWorkflowClaimInput({
        demoCase,
        uploads: uploadPayload,
        corpus,
      });

      claimInput.patientName = form.patientName;
      claimInput.policyNumber = form.policyNumber;
      claimInput.hospital = viewer?.name || form.hospital;
      claimInput.diagnosis = form.diagnosis;
      claimInput.amount = Number(form.requestedAmount);
      claimInput.serviceType = claimServiceType;
      claimInput.timeline =
        claimServiceType === "reimbursement"
          ? [
              { label: "Reimbursement packet assembled after discharge", time: new Date().toISOString(), actor: "hospital" },
              { label: "Insurer review queued", time: new Date(Date.now() + 10_000).toISOString(), actor: "system" },
            ]
          : claimInput.timeline;

      if (claimServiceType === "reimbursement") {
        claimInput.documents = currentDocRequirements.map((item) => ({
          name: uploads[item.slotId]?.fileName ?? `${item.slotId}.pdf`,
          type: uploads[item.slotId]?.type ?? "application/pdf",
          size: uploads[item.slotId]?.size ?? 100000,
          uploadedAt: new Date().toISOString(),
          uploadedBy: "hospital",
          category: item.label,
          uploadedFileName: uploads[item.slotId]?.fileName,
          processingStatus: "ready" as const,
        }));
      }

      const claim = await submitClaim(claimInput);
      setSelectedClaimId(claim.id);
      setActiveTab("track");
      toast.success(`Claim ${claim.id} sent to the insurer queue.`);
    } finally {
      setSubmitting(false);
    }
  };

  const handleAdmitPatient = (patientId: string) => {
    setOngoingPatients((current) =>
      current.map((p) =>
        p.id === patientId
          ? { ...p, phase: "admitted" as OngoingPatientPhase, insuranceNotified: true, initialPaymentPercent: Math.floor(Math.random() * 11) + 40 }
          : p,
      ),
    );
    toast.success("Insurance notified — 40-50% initial payment requested.");
  };

  const handleSendDischargeSummary = (patientId: string) => {
    const patient = ongoingPatients.find((p) => p.id === patientId);
    if (!patient) return;
    const summary: DischargeSummaryFields = {
      daysOfAdmission: Number(dischargeDraft.daysOfAdmission) || 3,
      medicines: (dischargeDraft.medicines as unknown as string[]) ?? ["Paracetamol 650mg QID"],
      diagnosis: dischargeDraft.diagnosis || patient.diagnosis,
      hospitalName: dischargeDraft.hospitalName || "City Care Hospital, Mumbai",
      admissionDate: patient.admissionDate,
      dischargeDate: dischargeDraft.dischargeDate || new Date().toISOString().split("T")[0],
      attendingDoctor: dischargeDraft.attendingDoctor || "Dr. Rakesh Iyer",
      finalBillAmount: patient.billingItems.reduce((s, b) => s + b.amount, 0),
    };
    setOngoingPatients((current) =>
      current.map((p) => (p.id === patientId ? { ...p, dischargeSummary: summary } : p)),
    );
    setDischargeDraft({});
    toast.success("Discharge summary generated and sent to Insurance.");
  };

  if (!ready || !viewer) {
    return (
      <div className="space-y-4">
        <div className="space-y-2">
          <SkeletonBlock className="h-10 w-72" />
          <SkeletonBlock className="h-5 w-64" />
        </div>
        <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
          {Array.from({ length: 4 }).map((_, index) => <SkeletonCard key={index} lines={2} />)}
        </div>
      </div>
    );
  }

  return (
    <div className="relative isolate space-y-5 lg:space-y-6">
      <div className="pointer-events-none absolute inset-x-0 top-0 -z-10 h-[320px] bg-[radial-gradient(circle_at_top_left,rgba(90,151,216,0.14),transparent_40%),radial-gradient(circle_at_top_right,rgba(34,197,94,0.08),transparent_34%)]" />

      {/* ── Hero banner ── */}
      <DashboardCard visual="plain" surfaceClassName="bg-[linear-gradient(132deg,#0e2e4f_0%,#13548a_48%,#1d7ca8_100%)]" className="overflow-hidden border-slate-800/10 text-white shadow-[0_24px_60px_rgba(16,35,60,0.2)]">
        <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
          <div className="max-w-2xl">
            <p className="text-[11px] font-medium uppercase tracking-[0.16em] text-white/65">Hospital operations cockpit</p>
            <h2 className="mt-2 text-[24px] font-semibold tracking-[-0.04em] text-white">Run hospital cashless operations cleanly and hand off discharge-ready reimbursement packs.</h2>
            <p className="mt-3 text-sm leading-6 text-white/78">Cashless stays move from AL generation to admit, tests, billing, and discharge summary to insurance. Reimbursement stays are packaged after discharge, while patient queries stay with the patient.</p>
            <div className="mt-4 flex flex-wrap gap-2">
              <div className="rounded-full border border-white/12 bg-white/10 px-3 py-1.5 text-[11px] font-medium text-white/86">
                {ongoingCount} ongoing patients
              </div>
              <div className="rounded-full border border-white/12 bg-white/10 px-3 py-1.5 text-[11px] font-medium text-white/86">
                {awaitingDischarge} in-stay cashless
              </div>
              <div className="rounded-full border border-white/12 bg-white/10 px-3 py-1.5 text-[11px] font-medium text-white/86">
                NPI {hospitalVerificationReady ? "trustworthy" : "pending"}
              </div>
              <div className="rounded-full border border-white/12 bg-white/10 px-3 py-1.5 text-[11px] font-medium text-white/86">
                40-50% initial insurer release
              </div>
            </div>
          </div>
          <div className="flex flex-wrap gap-2">
            {([
              { key: "ongoing", label: "Ongoing patients", icon: Users },
              { key: "submit", label: "Submit claim", icon: FileText },
              { key: "track", label: "Track claims", icon: ClipboardList },
            ] as const).map((tab) => (
              <button
                key={tab.key}
                type="button"
                onClick={() => setActiveTab(tab.key)}
                className={`inline-flex items-center gap-1.5 rounded-full px-3 py-1.5 text-[12px] font-medium transition ${activeTab === tab.key ? "bg-white text-[var(--ch-blue-dark)] shadow-[0_14px_28px_rgba(16,35,60,0.2)]" : "border border-white/14 bg-white/10 text-white/80 hover:bg-white/16"}`}
              >
                <tab.icon className="h-3.5 w-3.5" />
                {tab.label}
              </button>
            ))}
          </div>
        </div>
      </DashboardCard>

      {/* ── Metric cards ── */}
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-5">
        {commandStats.map((item) => (
          <MetricCard
            key={item.label}
            label={item.label}
            value={item.value}
            helper={item.helper}
            tone={item.tone}
            badge={item.badge}
            className={item.className}
            valueClassName={item.valueClassName}
          />
        ))}
      </div>

      <div className="grid gap-4 xl:grid-cols-[0.9fr_1.1fr]">
        <DashboardCard className="bg-[linear-gradient(180deg,#ffffff_0%,#eef6ff_100%)]">
          <p className="text-[11px] uppercase tracking-[0.16em] text-slate-500">Registration trust</p>
          <p className="mt-2 text-[18px] font-semibold tracking-[-0.03em] text-slate-900">
            {hospitalVerificationReady ? "Hospital identity verified" : "Complete hospital verification"}
          </p>
          <p className="mt-2 text-sm leading-6 text-slate-600">
            Registration in this workflow depends on hospital registration plus NPI. Once both are present, the workspace is treated as trustworthy for claim submission.
          </p>
          <div className="mt-4 flex flex-wrap gap-2">
            <span className={`rounded-full px-3 py-1.5 text-[11px] font-semibold ${viewer.hospitalRegistrationId ? "bg-green-50 text-green-700" : "bg-amber-50 text-amber-700"}`}>
              Registration ID {viewer.hospitalRegistrationId ? "ready" : "missing"}
            </span>
            <span className={`rounded-full px-3 py-1.5 text-[11px] font-semibold ${viewer.npi ? "bg-green-50 text-green-700" : "bg-amber-50 text-amber-700"}`}>
              NPI {viewer.npi ? "trustworthy" : "missing"}
            </span>
          </div>
        </DashboardCard>

        <DashboardCard className="bg-[linear-gradient(180deg,#ffffff_0%,#f7fbff_100%)]">
          <p className="text-[11px] uppercase tracking-[0.16em] text-slate-500">Hospital flow blueprint</p>
          <div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">
            {hospitalCashlessFlow.map((step) => (
              <div key={step} className="rounded-[14px] border border-slate-200 bg-white p-3 shadow-[0_10px_24px_rgba(15,23,42,0.04)]">
                <p className="text-sm leading-6 text-slate-700">{step}</p>
              </div>
            ))}
          </div>
        </DashboardCard>
      </div>

      {/* ══════════════════════════════════════════════════════════════════ */}
      {/* TAB: Ongoing Patients                                            */}
      {/* ══════════════════════════════════════════════════════════════════ */}
      {activeTab === "ongoing" ? (
        <div className="grid gap-4 xl:grid-cols-[340px_minmax(0,1fr)]">
          {/* ── Patient list ── */}
          <DashboardCard>
            <div>
              <p className="text-[11px] uppercase tracking-[0.16em] text-slate-500">Cashless cases</p>
              <p className="mt-2 text-[15px] font-semibold text-slate-900">Ongoing patient registry</p>
            </div>
            <div className="mt-4 space-y-2">
              {ongoingPatients.map((patient) => {
                const selected = patient.id === selectedPatient?.id;
                return (
                  <button
                    key={patient.id}
                    type="button"
                    onClick={() => setSelectedPatientId(patient.id)}
                    className={`w-full rounded-[14px] border p-3 text-left transition ${selected ? "border-blue-200 bg-blue-50 shadow-[inset_3px_0_0_#2C6BE4]" : "border-slate-200 bg-white hover:bg-slate-50"}`}
                  >
                    <div className="flex items-start justify-between gap-2">
                      <div>
                        <p className="text-sm font-medium text-slate-900">{patient.patientName}</p>
                        <p className="mt-1 text-[11px] text-slate-500">{patient.alNumber}</p>
                      </div>
                      <StatusChip label={PHASE_LABELS[patient.phase]} tone={phaseTone(patient.phase)} />
                    </div>
                    <p className="mt-2 text-[12px] text-slate-600 line-clamp-1">{patient.diagnosis}</p>
                  </button>
                );
              })}
            </div>
          </DashboardCard>

          {/* ── Selected patient detail ── */}
          {selectedPatient ? (
            <div className="space-y-4">
              {/* Header */}
              <DashboardCard className="bg-[linear-gradient(180deg,#ffffff_0%,#f7fbff_100%)]">
                <div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between">
                  <div>
                    <p className="text-[11px] uppercase tracking-[0.16em] text-slate-500">Patient detail</p>
                    <p className="text-[18px] font-semibold text-slate-900">{selectedPatient.patientName}</p>
                    <div className="mt-2 flex flex-wrap gap-2 text-[12px] text-slate-600">
                      <span className="rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1 font-medium">AL: {selectedPatient.alNumber}</span>
                      <span className="rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1">Policy: {selectedPatient.policyNumber}</span>
                      <span className="rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1">Admitted: {selectedPatient.admissionDate}</span>
                    </div>
                    <p className="mt-2 text-sm text-slate-700">{selectedPatient.diagnosis}</p>
                  </div>
                  <div className="flex items-center gap-2">
                    <StatusChip label={PHASE_LABELS[selectedPatient.phase]} tone={phaseTone(selectedPatient.phase)} />
                    {selectedPatient.insuranceNotified ? (
                      <span className="rounded-full border border-green-200 bg-green-50 px-2.5 py-1 text-[11px] font-semibold text-green-700">
                        Insurance: {selectedPatient.initialPaymentPercent}% released
                      </span>
                    ) : null}
                  </div>
                </div>

                {/* Phase progress */}
                <div className="mt-4">
                  <StepTracker
                    steps={PHASE_ORDER.map((phase) => ({
                      label: PHASE_LABELS[phase],
                      state: PHASE_ORDER.indexOf(phase) < PHASE_ORDER.indexOf(selectedPatient.phase)
                        ? "complete" as const
                        : PHASE_ORDER.indexOf(phase) === PHASE_ORDER.indexOf(selectedPatient.phase)
                          ? "active" as const
                          : "upcoming" as const,
                    }))}
                    activeIndex={PHASE_ORDER.indexOf(selectedPatient.phase)}
                  />
                </div>
              </DashboardCard>

              {/* Pre-Admission Documents */}
              <DashboardCard>
                <p className="text-[14px] font-medium text-slate-900">Pre-admission documents</p>
                <p className="mt-1 text-[12px] text-slate-500">Re-auth Form, Prescription, and Diagnoses required before admission.</p>
                <div className="mt-3 space-y-2">
                  {selectedPatient.preAdmissionDocs.map((doc) => (
                    <div key={doc.label} className="flex items-center justify-between rounded-[12px] border border-slate-200 bg-slate-50 px-3 py-2.5">
                      <div className="flex items-center gap-2">
                        <div className={`flex h-7 w-7 items-center justify-center rounded-full ${doc.uploaded ? "bg-green-100 text-green-600" : "bg-slate-200 text-slate-400"}`}>
                          {doc.uploaded ? <Check className="h-3.5 w-3.5" /> : <Minus className="h-3.5 w-3.5" />}
                        </div>
                        <span className="text-sm text-slate-700">{doc.label}</span>
                      </div>
                      <span className={`text-[11px] font-semibold ${doc.uploaded ? "text-green-600" : "text-slate-400"}`}>
                        {doc.uploaded ? "Uploaded" : "Missing"}
                      </span>
                    </div>
                  ))}
                </div>

                {/* Patient Admit trigger */}
                {selectedPatient.phase === "pre_admission" && selectedPatient.preAdmissionDocs.every((d) => d.uploaded) ? (
                  <div className="mt-4">
                    <button
                      type="button"
                      onClick={() => handleAdmitPatient(selectedPatient.id)}
                      className="w-full rounded-[14px] bg-[var(--ch-blue)] px-4 py-3 text-sm font-semibold text-white shadow-[0_16px_28px_rgba(90,151,216,0.22)]"
                    >
                      <Stethoscope className="mr-2 inline h-4 w-4" />
                      Admit Patient — Notify Insurance (40-50% initial payment)
                    </button>
                  </div>
                ) : selectedPatient.phase === "pre_admission" ? (
                  <p className="mt-3 text-[12px] text-amber-700">Complete all pre-admission documents before admitting the patient.</p>
                ) : null}
              </DashboardCard>

              {/* Tests — During Admission */}
              {selectedPatient.phase !== "pre_admission" ? (
                <DashboardCard>
                  <p className="text-[14px] font-medium text-slate-900">Tests &amp; diagnostics</p>
                  <p className="mt-1 text-[12px] text-slate-500">Tests conducted during the hospital stay.</p>
                  <div className="mt-3 space-y-2">
                    {selectedPatient.tests.map((test) => (
                      <div key={test.name} className="rounded-[12px] border border-slate-200 bg-slate-50 p-3">
                        <div className="flex items-start justify-between gap-2">
                          <div>
                            <p className="text-sm font-medium text-slate-900">{test.name}</p>
                            {test.result ? <p className="mt-1 text-[12px] text-slate-600">{test.result}</p> : null}
                          </div>
                          <StatusChip
                            label={test.status === "completed" ? "Done" : test.status === "ordered" ? "Ordered" : "Pending"}
                            tone={test.status === "completed" ? "green" : test.status === "ordered" ? "blue" : "amber"}
                          />
                        </div>
                        {test.date ? <p className="mt-1 text-[11px] text-slate-400">{test.date}</p> : null}
                      </div>
                    ))}
                  </div>
                </DashboardCard>
              ) : null}

              {/* Billing — During Admission */}
              {selectedPatient.billingItems.length > 0 ? (
                <DashboardCard>
                  <div className="flex items-center justify-between">
                    <div>
                      <p className="text-[14px] font-medium text-slate-900">Billing items</p>
                      <p className="mt-1 text-[12px] text-slate-500">Running bill for the current admission.</p>
                    </div>
                    <span className="text-sm font-semibold text-slate-900">
                      Total: {formatCurrency(selectedPatient.billingItems.reduce((s, b) => s + b.amount, 0))}
                    </span>
                  </div>
                  <div className="mt-3 overflow-hidden rounded-[14px] border border-slate-200 bg-white">
                    <div className="grid grid-cols-[1fr_80px_100px] gap-2 border-b border-slate-200 bg-slate-50 px-3 py-2 text-[11px] uppercase tracking-[0.08em] text-slate-500">
                      <span>Item</span>
                      <span>Category</span>
                      <span className="text-right">Amount</span>
                    </div>
                    {selectedPatient.billingItems.map((item) => (
                      <div key={item.item} className="grid grid-cols-[1fr_80px_100px] gap-2 border-b border-slate-100 px-3 py-2.5 text-sm last:border-b-0">
                        <span className="text-slate-700">{item.item}</span>
                        <span className="capitalize text-slate-500 text-[11px]">{item.category}</span>
                        <span className="text-right font-medium text-slate-900">{formatCurrency(item.amount)}</span>
                      </div>
                    ))}
                  </div>
                </DashboardCard>
              ) : null}

              {/* Discharge Summary */}
              {selectedPatient.phase === "discharge" || selectedPatient.phase === "during_stay" ? (
                <DashboardCard className="bg-[linear-gradient(180deg,#ffffff_0%,#f0faf4_100%)]">
                  <p className="text-[14px] font-medium text-slate-900">Discharge summary</p>
                  <p className="mt-1 text-[12px] text-slate-500">Final document sent to Insurance for settlement.</p>

                  {selectedPatient.dischargeSummary ? (
                    <div className="mt-3 space-y-2">
                      <div className="rounded-[14px] border border-green-200 bg-green-50 p-4">
                        <div className="flex items-center gap-2">
                          <Check className="h-4 w-4 text-green-600" />
                          <p className="text-sm font-semibold text-green-700">Discharge summary generated and sent</p>
                        </div>
                        <div className="mt-3 grid gap-2 sm:grid-cols-2 text-[12px] text-slate-700">
                          <p><span className="text-slate-500">Days:</span> {selectedPatient.dischargeSummary.daysOfAdmission}</p>
                          <p><span className="text-slate-500">Doctor:</span> {selectedPatient.dischargeSummary.attendingDoctor}</p>
                          <p><span className="text-slate-500">Diagnosis:</span> {selectedPatient.dischargeSummary.diagnosis}</p>
                          <p><span className="text-slate-500">Bill:</span> {formatCurrency(selectedPatient.dischargeSummary.finalBillAmount)}</p>
                        </div>
                        <div className="mt-2">
                          <p className="text-[11px] text-slate-500">Medicines: {selectedPatient.dischargeSummary.medicines.join(", ")}</p>
                        </div>
                      </div>
                    </div>
                  ) : (
                    <div className="mt-3 space-y-3">
                      <div className="grid gap-3 sm:grid-cols-2">
                        <label className="text-[12px] text-slate-600">
                          No. of days
                          <input
                            type="number"
                            value={dischargeDraft.daysOfAdmission ?? ""}
                            onChange={(e) => setDischargeDraft((d) => ({ ...d, daysOfAdmission: Number(e.target.value) }))}
                            placeholder="e.g. 3"
                            className="mt-1 h-10 w-full rounded-[12px] border border-slate-200 bg-white px-3 text-sm outline-none focus:border-[var(--ch-blue)]"
                          />
                        </label>
                        <label className="text-[12px] text-slate-600">
                          Discharge date
                          <input
                            type="date"
                            value={dischargeDraft.dischargeDate ?? ""}
                            onChange={(e) => setDischargeDraft((d) => ({ ...d, dischargeDate: e.target.value }))}
                            className="mt-1 h-10 w-full rounded-[12px] border border-slate-200 bg-white px-3 text-sm outline-none focus:border-[var(--ch-blue)]"
                          />
                        </label>
                        <label className="text-[12px] text-slate-600 sm:col-span-2">
                          Diagnosis
                          <input
                            value={dischargeDraft.diagnosis ?? selectedPatient.diagnosis}
                            onChange={(e) => setDischargeDraft((d) => ({ ...d, diagnosis: e.target.value }))}
                            className="mt-1 h-10 w-full rounded-[12px] border border-slate-200 bg-white px-3 text-sm outline-none focus:border-[var(--ch-blue)]"
                          />
                        </label>
                        <label className="text-[12px] text-slate-600 sm:col-span-2">
                          Medicines (comma-separated)
                          <input
                            value={Array.isArray(dischargeDraft.medicines) ? dischargeDraft.medicines.join(", ") : ""}
                            onChange={(e) => setDischargeDraft((d) => ({ ...d, medicines: e.target.value.split(",").map((s) => s.trim()) as unknown as string[] }))}
                            placeholder="e.g. Paracetamol 650mg, Ceftriaxone 1g"
                            className="mt-1 h-10 w-full rounded-[12px] border border-slate-200 bg-white px-3 text-sm outline-none focus:border-[var(--ch-blue)]"
                          />
                        </label>
                        <label className="text-[12px] text-slate-600">
                          Attending doctor
                          <input
                            value={dischargeDraft.attendingDoctor ?? ""}
                            onChange={(e) => setDischargeDraft((d) => ({ ...d, attendingDoctor: e.target.value }))}
                            placeholder="Dr. Name"
                            className="mt-1 h-10 w-full rounded-[12px] border border-slate-200 bg-white px-3 text-sm outline-none focus:border-[var(--ch-blue)]"
                          />
                        </label>
                        <label className="text-[12px] text-slate-600">
                          Hospital name
                          <input
                            value={dischargeDraft.hospitalName ?? "City Care Hospital, Mumbai"}
                            onChange={(e) => setDischargeDraft((d) => ({ ...d, hospitalName: e.target.value }))}
                            className="mt-1 h-10 w-full rounded-[12px] border border-slate-200 bg-white px-3 text-sm outline-none focus:border-[var(--ch-blue)]"
                          />
                        </label>
                      </div>
                      <button
                        type="button"
                        onClick={() => handleSendDischargeSummary(selectedPatient.id)}
                        className="w-full rounded-[14px] bg-green-600 px-4 py-3 text-sm font-semibold text-white shadow-[0_16px_28px_rgba(34,197,94,0.22)]"
                      >
                        <Send className="mr-2 inline h-4 w-4" />
                        Generate &amp; send discharge summary to Insurance
                      </button>
                    </div>
                  )}
                </DashboardCard>
              ) : null}
            </div>
          ) : (
            <DashboardCard>
              <div className="flex min-h-[240px] flex-col items-center justify-center text-center">
                <CircleDashed className="h-6 w-6 text-slate-400" />
                <p className="mt-3 text-sm text-slate-500">Select a patient to view their admission journey.</p>
              </div>
            </DashboardCard>
          )}
        </div>
      ) : null}

      {/* ══════════════════════════════════════════════════════════════════ */}
      {/* TAB: Submit Claim                                                */}
      {/* ══════════════════════════════════════════════════════════════════ */}
      {activeTab === "submit" ? (
        <div className="space-y-4">
          {/* Claim Type selector */}
          <DashboardCard>
            <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
              <div>
                <p className="text-[14px] font-medium text-slate-900">Claim type</p>
                <p className="mt-1 text-[12px] text-slate-500">Cashless stays are managed by hospital operations. Reimbursement packs are assembled after discharge and queries are handled by the patient.</p>
              </div>
              <div className="flex gap-2">
                {(["cashless", "reimbursement"] as ClaimServiceType[]).map((svc) => (
                  <button
                    key={svc}
                    type="button"
                    onClick={() => { setClaimServiceType(svc); setUploads({}); }}
                    className={`rounded-full px-4 py-2 text-[12px] font-semibold capitalize transition ${claimServiceType === svc ? "bg-[var(--ch-blue)] text-white shadow-[0_10px_24px_rgba(74,142,219,0.18)]" : "border border-slate-200 bg-white text-slate-600 hover:border-slate-300"}`}
                  >
                    {svc}
                  </button>
                ))}
              </div>
            </div>
            {claimServiceType === "reimbursement" ? (
              <div className="mt-3 rounded-[12px] border border-amber-200 bg-amber-50 p-3 text-[12px] text-amber-800">
                ⚠️ <strong>Reimbursement:</strong> Collect all hospital documents after discharge, attach prescription and additional form, and make the discharge summary complete. If insurance raises a query later, the patient handles it themselves.
              </div>
            ) : null}
          </DashboardCard>

          <div className="grid gap-4 xl:grid-cols-[1.05fr_0.95fr]">
            {/* Patient details form */}
            <DashboardCard className="bg-[linear-gradient(180deg,#ffffff_0%,var(--ch-blue-light)_100%)]">
              <p className="text-[14px] font-medium text-slate-900">Patient and claim details</p>
              <p className="mt-1 text-[12px] text-slate-500">
                {claimServiceType === "cashless"
                  ? "Capture the essentials that support AL generation, admit notification, and insurer handoff."
                  : "Capture the post-discharge reimbursement essentials before the packet is pushed forward."}
              </p>

              <div className="mt-4 grid gap-3 md:grid-cols-2">
                <label className="text-[12px] text-slate-600">
                  Patient name
                  <input value={form.patientName} onChange={(event) => setForm((current) => ({ ...current, patientName: event.target.value }))} className="mt-1 h-11 w-full rounded-[14px] border border-slate-200 bg-white px-3 text-sm outline-none focus:border-[var(--ch-blue)]" />
                </label>
                <label className="text-[12px] text-slate-600">
                  Policy number
                  <input value={form.policyNumber} onChange={(event) => setForm((current) => ({ ...current, policyNumber: event.target.value }))} className="mt-1 h-11 w-full rounded-[14px] border border-slate-200 bg-white px-3 text-sm outline-none focus:border-[var(--ch-blue)]" />
                </label>
                <label className="text-[12px] text-slate-600">
                  Hospital
                  <input value={form.hospital} onChange={(event) => setForm((current) => ({ ...current, hospital: event.target.value }))} className="mt-1 h-11 w-full rounded-[14px] border border-slate-200 bg-white px-3 text-sm outline-none focus:border-[var(--ch-blue)]" />
                </label>
                <label className="text-[12px] text-slate-600">
                  Requested amount
                  <input value={form.requestedAmount} type="number" onChange={(event) => setForm((current) => ({ ...current, requestedAmount: Number(event.target.value) }))} className="mt-1 h-11 w-full rounded-[14px] border border-slate-200 bg-white px-3 text-sm outline-none focus:border-[var(--ch-blue)]" />
                </label>
                <label className="text-[12px] text-slate-600 md:col-span-2">
                  Diagnosis
                  <textarea value={form.diagnosis} onChange={(event) => setForm((current) => ({ ...current, diagnosis: event.target.value }))} className="mt-1 min-h-32 w-full rounded-[14px] border border-slate-200 bg-white px-3 py-3 text-sm outline-none focus:border-[var(--ch-blue)]" />
                </label>
              </div>
            </DashboardCard>

            {/* Document checklist */}
            <div className="space-y-4">
              <DashboardCard>
                <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
                  <div>
                    <p className="text-[14px] font-medium text-slate-900">Document checklist</p>
                    <p className="mt-1 text-[12px] text-slate-500">
                      {claimServiceType === "reimbursement"
                        ? "All hospital documents, prescription, additional form, and discharge summary are required after discharge."
                        : "Files move from missing to scanning to ready, and flagged fields stay visible."}
                    </p>
                  </div>
                  <StatusChip label={`${readyDocuments} of ${currentDocRequirements.length} ready`} tone={readyDocuments === currentDocRequirements.length ? "green" : "amber"} />
                </div>

                <div className="mt-4 space-y-3">
                  {currentDocRequirements.map((requirement) => {
                    const upload = uploads[requirement.slotId];
                    const status = upload?.status ?? "missing";
                    const toneWrap =
                      status === "ready"
                        ? "bg-green-50 text-green-700"
                        : status === "issue"
                          ? "bg-red-50 text-red-600"
                          : status === "scanning"
                            ? "bg-amber-50 text-amber-700"
                            : "bg-slate-100 text-slate-500";

                    return (
                      <div key={requirement.slotId} className="rounded-[14px] border border-slate-200 bg-slate-50 p-3">
                        <div className="flex flex-col gap-3 xl:flex-row xl:items-start xl:justify-between">
                          <div className="flex items-start gap-3">
                            <div className={`flex h-9 w-9 items-center justify-center rounded-full ${toneWrap}`}>
                              {status === "ready" ? (
                                <Check className="h-4 w-4" />
                              ) : status === "issue" ? (
                                <AlertTriangle className="h-4 w-4" />
                              ) : status === "scanning" ? (
                                <LoaderCircle className="h-4 w-4 animate-spin" />
                              ) : (
                                <Minus className="h-4 w-4" />
                              )}
                            </div>
                            <div>
                              <p className="text-sm font-medium text-slate-900">{requirement.label}</p>
                              <p className="mt-1 text-[12px] text-slate-500">
                                {upload ? `${upload.fileName} - ${Math.max(1, Math.round(upload.size / 1024))} KB` : "No file uploaded yet"}
                              </p>
                            </div>
                          </div>
                          <div className="flex flex-wrap gap-2">
                            <label className="inline-flex cursor-pointer items-center gap-1 rounded-[12px] border border-slate-200 bg-white px-3 py-2 text-[12px] font-medium text-slate-700">
                              <Upload className="h-3.5 w-3.5" />
                              {upload ? "Replace" : "Upload"}
                              <input type="file" accept=".pdf,application/pdf" className="hidden" onChange={(event) => handleFileSelect(requirement.slotId, event.target.files?.[0])} />
                            </label>
                            {status !== "missing" ? (
                              <button type="button" onClick={() => removeUpload(requirement.slotId)} className="rounded-[12px] border border-slate-200 bg-white px-3 py-2 text-[12px] font-medium text-slate-700">
                                <Trash2 className="h-3.5 w-3.5" />
                              </button>
                            ) : null}
                          </div>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </DashboardCard>

              <DashboardCard className="bg-[linear-gradient(180deg,#ffffff_0%,#f3f9ff_100%)]">
                <p className="text-[14px] font-medium text-slate-900">Submission confidence</p>
                <p className="mt-1 text-[12px] text-slate-500">
                  Confidence {submissionConfidence}% — {claimServiceType === "reimbursement" ? "Discharge summary is the critical reimbursement document and must include days, medicine, diagnosis, and hospital." : scenarioId === "case-3" ? "All documents verified, no billing anomalies detected." : scenarioId === "case-2" ? "Billing amount exceeds the allowed treatment pattern and should be reviewed." : "Coverage timing may require policy continuity proof."}
                </p>
                <div className="mt-4">
                  <ConfidenceBar label="Confidence" value={submissionConfidence} tone={confidenceTone} />
                </div>
              </DashboardCard>

              {claimServiceType === "reimbursement" ? (
                <DashboardCard className="bg-[linear-gradient(180deg,#ffffff_0%,#fff8eb_100%)]">
                  <p className="text-[14px] font-medium text-slate-900">Critical discharge summary fields</p>
                  <p className="mt-1 text-[12px] text-slate-500">These fields are mandatory for the reimbursement track before anything is sent forward.</p>
                  <div className="mt-4 grid gap-2 sm:grid-cols-2">
                    {reimbursementCriticalFields.map((field) => (
                      <div key={field} className="rounded-[12px] border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-700">
                        {field}
                      </div>
                    ))}
                  </div>
                  <div className="mt-4 rounded-[12px] border border-amber-200 bg-amber-50 px-3 py-3 text-[12px] text-amber-800">
                    Query raised later: patient self-handles reimbursement clarifications.
                  </div>
                </DashboardCard>
              ) : null}

              <ActionPanel>
                <button
                  type="button"
                  onClick={handleSubmit}
                  disabled={!allRequiredUploaded || submitting}
                  title={!allRequiredUploaded ? "Upload every required document before submitting." : undefined}
                  className="w-full rounded-[14px] bg-[var(--ch-blue)] px-4 py-3 text-sm font-semibold text-white shadow-[0_16px_28px_rgba(90,151,216,0.22)] disabled:cursor-not-allowed disabled:opacity-45"
                >
                  {submitting ? "Submitting..." : claimServiceType === "cashless" ? "Submit cashless case to insurer" : "Send reimbursement packet to insurer"}
                </button>
                {!allRequiredUploaded ? (
                  <p className="mt-2 text-[11px] text-slate-500">All required documents must finish uploading before submission.</p>
                ) : hasDocumentIssues ? (
                  <p className="mt-2 text-[11px] text-amber-700">One document has a field that should be checked by the insurer during review.</p>
                ) : claimServiceType === "reimbursement" && reimbursementPacketReady ? (
                  <p className="mt-2 text-[11px] text-slate-500">Packet is complete. If the insurer asks a question later, the patient handles that reimbursement query directly.</p>
                ) : null}
              </ActionPanel>

              <DashboardCard className="bg-[linear-gradient(180deg,#ffffff_0%,#f7fbff_100%)]">
                <p className="text-[14px] font-medium text-slate-900">Auto-fetched records</p>
                <p className="mt-1 text-[12px] text-slate-500">These sections stay synced automatically, so hospital staff should not upload them again.</p>
                <div className="mt-4 grid gap-3 sm:grid-cols-2">
                  <div className="rounded-[12px] border border-slate-200 bg-white p-3">
                    <p className="text-[11px] uppercase tracking-[0.08em] text-slate-500">Fetched from patient side</p>
                    <p className="mt-2 text-sm text-slate-700">Policy number: {form.policyNumber}</p>
                    <p className="mt-1 text-sm text-slate-700">Patient identity moves with the shared claim record.</p>
                  </div>
                  <div className="rounded-[12px] border border-slate-200 bg-white p-3">
                    <p className="text-[11px] uppercase tracking-[0.08em] text-slate-500">Fetched from hospital profile</p>
                    <p className="mt-2 text-sm text-slate-700">Registration ID: {viewer.hospitalRegistrationId ?? "Missing"}</p>
                    <p className="mt-1 text-sm text-slate-700">NPI: {viewer.npi ?? "Missing"}</p>
                  </div>
                </div>
              </DashboardCard>
            </div>
          </div>
        </div>
      ) : null}

      {/* ══════════════════════════════════════════════════════════════════ */}
      {/* TAB: Track Claims                                                */}
      {/* ══════════════════════════════════════════════════════════════════ */}
      {activeTab === "track" ? (
        <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_340px]">
          <DashboardCard className="overflow-hidden p-0">
            <div className="hidden lg:block">
              <div className="grid grid-cols-[1fr_1fr_0.9fr_0.9fr_0.8fr_0.8fr] gap-3 border-b border-slate-200 bg-slate-50 px-4 py-3 text-[11px] uppercase tracking-[0.08em] text-slate-500">
                <span>Claim Process ID</span>
                <span>Patient</span>
                <span>Service</span>
                <span>Requested</span>
                <span>Status</span>
                <span>Days</span>
              </div>
              <div>
                {workflowClaims.length === 0 ? (
                  <div className="p-4 text-sm text-slate-500">Submitted claims will appear here.</div>
                ) : (
                  workflowClaims.map((claim) => (
                    <button
                      key={claim.id}
                      type="button"
                      onClick={() => setSelectedClaimId(claim.id)}
                      className={`grid w-full grid-cols-[1fr_1fr_0.9fr_0.9fr_0.8fr_0.8fr] gap-3 border-b border-slate-100 px-4 py-3 text-left text-sm ${selectedClaim?.id === claim.id ? "bg-[var(--ch-blue-light)]" : "bg-white hover:bg-slate-50"}`}
                    >
                      <span className="font-medium text-slate-900">{claim.claimProcessId ?? claim.id}</span>
                      <span className="text-slate-700">{claim.patientName}</span>
                      <span className="text-slate-600 capitalize">{claim.serviceType ?? "cashless"}</span>
                      <span className="text-slate-700">{formatCurrency(claim.amount)}</span>
                      <span><StatusChip label={claim.status.replace("_", " ")} tone={statusChipTone(claim.status)} /></span>
                      <span className="text-slate-500">{Math.max(1, Math.ceil((Date.now() - new Date(claim.submittedAt).getTime()) / 86400000))}</span>
                    </button>
                  ))
                )}
              </div>
            </div>

            <div className="space-y-3 p-4 lg:hidden">
              {workflowClaims.length === 0 ? (
                <div className="text-sm text-slate-500">Submitted claims will appear here.</div>
              ) : (
                workflowClaims.map((claim) => (
                  <button
                    key={`mobile-${claim.id}`}
                    type="button"
                    onClick={() => setSelectedClaimId(claim.id)}
                    className={`w-full rounded-[14px] border p-3 text-left ${selectedClaim?.id === claim.id ? "border-[var(--ch-blue-border)] bg-[var(--ch-blue-light)]" : "border-slate-200 bg-white"}`}
                  >
                    <div className="flex items-start justify-between gap-3">
                      <div>
                        <p className="text-sm font-medium text-slate-900">{claim.claimProcessId ?? claim.id}</p>
                        <p className="mt-1 text-[12px] text-slate-500">{claim.patientName}</p>
                      </div>
                      <StatusChip label={claim.status.replace("_", " ")} tone={statusChipTone(claim.status)} />
                    </div>
                    <div className="mt-3 grid gap-2 sm:grid-cols-2 text-[12px] text-slate-600">
                      <p>Requested: {formatCurrency(claim.amount)}</p>
                      <p>Service: {claim.serviceType ?? "cashless"}</p>
                    </div>
                  </button>
                ))
              )}
            </div>
          </DashboardCard>

          <DashboardCard>
            {selectedClaim ? (
              <div className="space-y-4">
                <div>
                  <p className="text-[15px] font-semibold text-slate-900">{selectedClaim.patientName}</p>
                  <p className="mt-1 text-[12px] text-slate-500">{selectedClaim.claimProcessId ?? selectedClaim.id} - {selectedClaim.hospital}</p>
                  <div className="mt-2 flex flex-wrap gap-2">
                    <span className="rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1 text-[11px] font-medium text-slate-600 capitalize">
                      {selectedClaim.serviceType ?? "cashless"}
                    </span>
                    <span className="rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1 text-[11px] font-medium text-slate-600">
                      {selectedClaim.serviceType === "reimbursement" ? "Patient handles insurer query" : "Hospital handles insurer query"}
                    </span>
                  </div>
                </div>
                <StepTracker steps={trackSteps(selectedClaim)} activeIndex={trackSteps(selectedClaim).findIndex((step) => step.state === "active")} />
                <div>
                  <p className="text-[12px] font-medium text-slate-900">Insurer messages</p>
                  <div className="mt-3 space-y-2">
                    {selectedClaim.timeline.filter((entry) => entry.actor === "insurer").length === 0 ? (
                      <p className="text-sm text-slate-500">No insurer messages yet.</p>
                    ) : (
                      selectedClaim.timeline
                        .filter((entry) => entry.actor === "insurer")
                        .map((entry, index) => (
                          <div key={`${entry.time}-${index}`} className="rounded-[14px] border border-slate-200 bg-slate-50 p-3">
                            <p className="text-sm text-slate-700">{entry.label}</p>
                            <p className="mt-1 text-[11px] text-slate-500">{formatRelativeTime(entry.time)}</p>
                          </div>
                        ))
                    )}
                  </div>
                </div>

                <div>
                  <p className="text-[12px] font-medium text-slate-900">Shared claim documents</p>
                  <div className="mt-3 space-y-2">
                    {selectedClaimDocuments.length === 0 ? (
                      <p className="text-sm text-slate-500">No shared documents yet.</p>
                    ) : (
                      selectedClaimDocuments.map((document) => (
                        <div key={`${document.name}-${document.uploadedAt}`} className="rounded-[14px] border border-slate-200 bg-slate-50 p-3">
                          <p className="text-sm text-slate-700">{document.category ?? document.name}</p>
                          <p className="mt-1 text-[11px] text-slate-500">
                            {document.uploadedBy} - {Math.max(1, Math.round(document.size / 1024))} KB - {formatRelativeTime(document.uploadedAt)}
                          </p>
                        </div>
                      ))
                    )}
                  </div>
                </div>

                <div className="rounded-[14px] border border-slate-200 bg-slate-50 p-3">
                  <p className="text-[12px] font-medium text-slate-900">Query handling</p>
                  <p className="mt-2 text-[12px] leading-6 text-slate-600">
                    {selectedClaimRequest
                      ? `Latest insurer request: ${selectedClaimRequest.note}`
                      : "No insurer document request is active on this claim."}
                  </p>
                  <p className="mt-2 text-[12px] text-slate-500">
                    {selectedClaimQueryOwner === "hospital"
                      ? "Cashless clarification stays with the hospital."
                      : "Reimbursement clarification stays with the patient."}
                  </p>
                  <div className="mt-3">
                    {hospitalCanUploadToClaim ? (
                      <label className="inline-flex cursor-pointer items-center gap-2 rounded-[12px] bg-[var(--ch-blue)] px-3 py-2 text-[12px] font-semibold text-white">
                        <Upload className="h-3.5 w-3.5" />
                        Upload requested PDF
                        <input type="file" accept=".pdf,application/pdf" className="hidden" onChange={(event) => handleRespondToInsurerRequest(event.target.files?.[0])} />
                      </label>
                    ) : (
                      <span className="rounded-[12px] border border-slate-200 bg-white px-3 py-2 text-[12px] font-medium text-slate-600">
                        {selectedClaimRequest ? "Patient handles this insurer request" : "No upload needed"}
                      </span>
                    )}
                  </div>
                </div>
              </div>
            ) : (
              <div className="flex min-h-[240px] flex-col items-center justify-center text-center">
                <CircleDashed className="h-6 w-6 text-slate-400" />
                <p className="mt-3 text-sm text-slate-500">Select a submitted claim to see its progress.</p>
              </div>
            )}
          </DashboardCard>
        </div>
      ) : null}
    </div>
  );
}
